export const invoices = [
    {
        id: '1234545329',
        status: 'Pending',
        reason: 'Escort through dangerous territory',
        description: "The client needs protection while traveling through treacherous lands infested with monsters, bandits, or other hostile forces.",
        location: 'Abanasinia',
        payment: 20 ,
        startDate: '2023-12-23',
        endDate: '2023-12-25',
        hiredBy: 'Lira Shadowstep',
        hiredByEmail: 'lirashadowstep@mail.com',
    },
    {
        id: '4578154',
        status: 'Approved',
        reason: 'Retrieve a valuable artifact.',
        description: "The client seeks a skilled adventurer to recover a precious relic from a forgotten tomb, ancient ruin, or guarded fortress.",
        location: 'Istars',
        payment: 23,
        startDate: '2024-10-23',
        endDate: '2024-10-27',
        hiredBy: 'Evelyn Swiftarrow',
    },
    {
        id: '8958745',
        status: 'In Progress',
        reason: 'Investigate mysterious occurrences.',
        description: "Strange phenomena, disappearances, or sightings of supernatural creatures prompt the client to hire an investigator to uncover the truth.",
        location: 'Thorbardin',
        payment: 54 ,
        startDate: '2024-04-07',
        endDate: '2024-04-17',
        hiredBy: 'Evelyn Swiftarrow',
    },
    {
        id: '8545785245',
        status: 'Approved',
        reason: 'Explore uncharted territories',
        description: "The client wishes to explore unknown lands, discover hidden treasures, or map out unexplored regions, requiring the expertise of an experienced explorer or scout.",
        location: 'Thorbardin',
        payment: 54,
        startDate: '2024-05-07',
        endDate: '2024-05-10',
        hiredBy: 'Eldric Brightspark',
    },
    {
        id: '4520254879',
        status: 'Approved',
        reason: 'Gather rare materials or ingredients',
        description: "The client requires exotic resources, magical components, or rare herbs for a special project or ritual, enlisting the help of an experienced gatherer or alchemist.",
        location: 'Tarsis',
        payment: 23,
        startDate: '2024-07-07',
        endDate: '2024-07-07',
        hiredBy: 'Evelyn Swiftarrow',
    },
    {
        id: '16985854258',
        status: 'Pending',
        reason: 'Solve a local conflict',
        description: "Civil unrest, political intrigue, or disputes between factions require the intervention of a mediator or negotiator to resolve peacefully.",
        location: 'Qualinesti',
        payment: 12 ,
        startDate: '2024-06-07',
        endDate: '2024-06-09',
        hiredBy: 'Thalindra Starlight',
    },
    {
        id: '2540125478',
        status: 'Pending',
        reason: 'Train local militia or adventurers',
        description: "The client seeks to bolster the defense of their community by hiring a seasoned warrior or expert trainer to instruct and prepare local fighters for battle.",
        location: 'Abanasinia',
        payment: 65,
        startDate: '2024-06-07',
        endDate: '2024-06-09',
        hiredBy: 'Eldric Brightspark',
    },
    {
        id: '5625687',
        status: 'Completed',
        reason: 'Perform a rescue mission',
        description: "A loved one or valuable ally has been captured or lost in enemy territory, prompting the client to hire a skilled rescuer to bring them safely home.",
        location: 'Northern Ergoth',
        payment: 34,
        startDate: '2023-06-09',
        endDate: '2023-06-12',
        hiredBy: 'Thalindra Starlight',
    },
]