export const invoices = [
    {
        id: '1234545329',
        status: 'Pending',
        reason: 'Escort through dangerous territory',
        location: 'Abanasinia',
        payment: 20 ,
        startDate: '2023-12-23',
        endDate: '2023-15-23',
        hiredBy: 'Lira Shadowstep',
    },
    {
        id: '4578154',
        status: 'Approved',
        reason: 'Retrieve a valuable artifact.',
        location: 'Istars',
        payment: 23,
        startDate: '2024-10-23',
        endDate: '2024-10-27',
        hiredBy: 'Evelyn Swiftarrow',
    },
    {
        id: '8958745',
        status: 'In Progress',
        reason: 'Investigate mysterious occurrences.',
        location: 'Thorbardin',
        payment: 54 ,
        startDate: '2024-04-07',
        endDate: '2024-04-17',
        hiredBy: 'Evelyn Swiftarrow',
    },
    {
        id: '8545785245',
        status: 'Approved',
        reason: 'Explore uncharted territories',
        location: 'Thorbardin',
        payment: 54,
        startDate: '2024-05-07',
        endDate: '2024-05-10',
        hiredBy: 'Eldric Brightspark',
    },
    {
        id: '4520254879',
        status: 'Approved',
        reason: 'Investigate mysterious occurrences',
        location: 'Tarsis',
        payment: 23,
        startDate: '2024-07-07',
        endDate: '2024-07-07',
        hiredBy: '',
    },
    {
        id: '16985854258',
        status: 'Pending',
        reason: 'Solve a local conflict',
        location: 'Qualinesti',
        payment: 12 ,
        startDate: '2024-06-07',
        endDate: '2024-06-09',
        hiredBy: 'Thalindra Starlight',
    },
    {
        id: '2540125478',
        status: 'Pending',
        reason: 'Train local militia or adventurers',
        location: 'Abanasinia',
        payment: 65,
        startDate: '2024-06-07',
        endDate: '2024-06-09',
        hiredBy: 'Eldric Brightspark',
    },
    {
        id: '5625687',
        status: 'Completed',
        reason: 'Perform a rescue mission',
        location: 'Northern Ergoth',
        payment: 34,
        startDate: '2023-06-09',
        endDate: '2023-06-12',
        hiredBy: 'Thalindra Starlight',
    },
]