// import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth/AuthProvider";
import HeaderMain from '@/components/layoutComponents/header/HeaderMain'
import { cinzel, roboto } from './fonts/fonts';

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Adventure Guild",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cinzel.variable} ${roboto.variable}  `}>
      
      <AuthProvider>
        <body >
          <HeaderMain />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
