// import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth/AuthProvider";
import HeaderMain from '@/components/layoutComponents/header/HeaderMain'
import { cinzel, roboto } from './fonts/fonts';
import GuildSideNavigation from "@/components/layoutComponents/sideNavs/guildSideNav/GuildSideNavigation";

// export const metadata = {
//   title: "Adventure Guild",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {

  return (
    <html lang="en" className={`${cinzel.variable} ${roboto.variable}  `}>
      <AuthProvider>
        <body >
          <HeaderMain />
          <div className="guild-member-page-layout-wrapper">
            <GuildSideNavigation/> 
            <main className="right-side-outer-wrapper">
              {children}
            </main>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
