import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from '@/components/layoutComponents/header/HeaderMain'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Adventure Guild",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain />
          {children}
        </body>
    </html>
  );
}
